# Generated by Django 5.1.7 on 2025-03-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owned_events_limit',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
