version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: manage_db
      POSTGRES_USER: maral
      POSTGRES_PASSWORD: Bushehr1383
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://maral:Bushehr1383@db:5432/manage_db

volumes:
  postgres_data:
